services:
  steward-bot:
    build: .
    restart: always
    env_file:
      - .env
    volumes:
      - ./logs:/usr/src/app/logs
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge
